version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "80:80"
    networks:
      - frontend-network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    networks:
      - backend-network
      - frontend-network
    environment:
      - MONGODB_URI=mongodb://mongo:27017/mydatabase
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    networks:
      - backend-network
    volumes:
      - mongo-data:/data/db

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge

volumes:
  mongo-data:
