// <auto-generated />
using System;
using Job_Portal_Application.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Job_Portal_Application.Migrations
{
    [DbContext(typeof(JobportalContext))]
    partial class JobportalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Job_Portal_Application.Models.AreasOfInterest", b =>
                {
                    b.Property<Guid>("AreasOfInterestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Lpa")
                        .HasColumnType("real");

                    b.Property<Guid>("TitleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AreasOfInterestId");

                    b.HasIndex("TitleId");

                    b.HasIndex("UserId");

                    b.ToTable("AreasOfInterests");
                });

            modelBuilder.Entity("Job_Portal_Application.Models.Company", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CompanyDescription")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CompanySize")
                        .HasColumnType("int");

                    b.Property<string>("CompanyWebsite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CredentialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyId");

                    b.HasIndex("CredentialId")
                        .IsUnique();

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Job_Portal_Application.Models.Credential", b =>
                {
                    b.Property<Guid>("CredentialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("HasCode")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("Password")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CredentialId");

                    b.ToTable("Credential");

                    b.HasData(
                        new
                        {
                            CredentialId = new Guid("bf0e4d0f-f8d4-4bb5-839e-2f34d9f6c6a4"),
                            HasCode = new byte[] { 199, 169, 68, 243, 93, 188, 147, 138, 101, 130, 72, 82, 48, 246, 37, 31, 223, 224, 206, 80, 121, 169, 139, 127, 47, 62, 177, 54, 143, 215, 23, 212, 20, 169, 16, 26, 81, 116, 195, 123, 55, 30, 27, 220, 45, 96, 231, 110, 77, 17, 145, 231, 93, 33, 154, 123, 134, 136, 69, 95, 179, 106, 149, 93, 126, 219, 208, 19, 222, 240, 12, 94, 163, 207, 136, 20, 237, 83, 19, 21, 175, 9, 44, 180, 107, 60, 141, 188, 182, 168, 65, 92, 236, 43, 163, 169, 244, 98, 228, 208, 164, 250, 223, 190, 29, 12, 184, 106, 210, 13, 48, 224, 241, 191, 135, 178, 198, 102, 224, 219, 178, 96, 253, 115, 142, 5, 48, 7 },
                            Password = new byte[] { 134, 175, 38, 11, 2, 167, 225, 82, 225, 193, 25, 153, 228, 204, 18, 163, 84, 161, 34, 59, 15, 188, 155, 183, 39, 94, 140, 210, 58, 20, 46, 67, 129, 185, 133, 31, 217, 166, 38, 24, 244, 166, 253, 103, 193, 114, 70, 71, 138, 251, 161, 225, 16, 89, 120, 63, 212, 237, 215, 15, 136, 98, 55, 236 },
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("Job_Portal_Application.Models.Education", b =>
                {
                    b.Property<Guid>("EducationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("EndYear")
                        .HasColumnType("date");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsCurrentlyStudying")
                        .HasColumnType("bit");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<float>("Percentage")
                        .HasColumnType("real");

                    b.Property<DateOnly>("StartYear")
                        .HasColumnType("date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EducationId");

                    b.HasIndex("UserId");

                    b.ToTable("Educations");
                });

            modelBuilder.Entity("Job_Portal_Application.Models.Experience", b =>
                {
                    b.Property<Guid>("ExperienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly>("EndYear")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartYear")
                        .HasColumnType("date");

                    b.Property<Guid>("TitleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ExperienceId");

                    b.HasIndex("TitleId");

                    b.HasIndex("UserId");

                    b.ToTable("Experiences");
                });

            modelBuilder.Entity("Job_Portal_Application.Models.Job", b =>
                {
                    b.Property<Guid>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DatePosted")
                        .HasColumnType("date");

                    b.Property<float?>("ExperienceRequired")
                        .HasColumnType("real");

                    b.Property<string>("JobDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("Lpa")
                        .HasColumnType("real");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<Guid>("TitleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("JobId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("TitleId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("Job_Portal_Application.Models.JobActivity", b =>
                {
                    b.Property<Guid>("JobApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("AppliedDate")
                        .HasColumnType("date");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ResumeViewed")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("JobApplicationId");

                    b.HasIndex("JobId");

                    b.HasIndex("UserId");

                    b.ToTable("JobActivities");
                });

            modelBuilder.Entity("Job_Portal_Application.Models.JobSkills", b =>
                {
                    b.Property<Guid>("JobSkillsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("JobSkillsId");

                    b.HasIndex("JobId");

                    b.HasIndex("SkillId");

                    b.ToTable("JobSkills");
                });

            modelBuilder.Entity("Job_Portal_Application.Models.Skill", b =>
                {
                    b.Property<Guid>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SkillId");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            SkillId = new Guid("625ab532-ebca-4b03-ad7f-98f9345577c3"),
                            SkillName = "HTML"
                        },
                        new
                        {
                            SkillId = new Guid("bae23ea9-5982-44d2-834d-5323bc77b8b2"),
                            SkillName = "CSS"
                        },
                        new
                        {
                            SkillId = new Guid("8e81710f-cacf-41b8-8195-63ecf8ea60fa"),
                            SkillName = "JavaScript"
                        },
                        new
                        {
                            SkillId = new Guid("7a55a442-c8d3-4a70-a889-2eca7cd5e302"),
                            SkillName = "TypeScript"
                        },
                        new
                        {
                            SkillId = new Guid("b17bf8fc-8ea0-4379-9075-e79743d5953e"),
                            SkillName = "React"
                        },
                        new
                        {
                            SkillId = new Guid("272bf54a-9557-456b-bf69-b59505d40554"),
                            SkillName = "Angular"
                        },
                        new
                        {
                            SkillId = new Guid("3cf4ec48-f487-4b72-8508-e23588be7b03"),
                            SkillName = "Vue"
                        },
                        new
                        {
                            SkillId = new Guid("b7936cf7-ec0d-4ce0-9733-f0e9f1235b5a"),
                            SkillName = "Node.js"
                        },
                        new
                        {
                            SkillId = new Guid("26dd9ab7-bdcd-40e9-b47e-0875a733996e"),
                            SkillName = "Express"
                        },
                        new
                        {
                            SkillId = new Guid("d69d35f8-41d4-400f-a490-dfabd0d67d51"),
                            SkillName = "Python"
                        },
                        new
                        {
                            SkillId = new Guid("4c8d4d51-73d0-4a81-bbb5-ec88fd707d5c"),
                            SkillName = "Django"
                        },
                        new
                        {
                            SkillId = new Guid("626a9ace-6dc1-4b0d-ba4a-03b4e844a870"),
                            SkillName = "Flask"
                        },
                        new
                        {
                            SkillId = new Guid("b8dd36b5-eeb5-43ac-9bcd-b16533475258"),
                            SkillName = "Java"
                        },
                        new
                        {
                            SkillId = new Guid("b5466c47-e190-4b4e-b0ea-b9f5b959ef64"),
                            SkillName = "Spring"
                        },
                        new
                        {
                            SkillId = new Guid("812ade95-7da8-4c00-8e7c-93603a8b7efa"),
                            SkillName = "Kotlin"
                        },
                        new
                        {
                            SkillId = new Guid("64ad8798-0131-4280-8a07-dad82b00ceba"),
                            SkillName = "Swift"
                        },
                        new
                        {
                            SkillId = new Guid("08d72cc1-1ae2-4648-86ad-3adabc19c591"),
                            SkillName = "Objective-C"
                        },
                        new
                        {
                            SkillId = new Guid("465df5a5-b3c0-4197-87b3-d593c9d20dde"),
                            SkillName = "Ruby"
                        },
                        new
                        {
                            SkillId = new Guid("2b89ed39-4a32-402d-8544-f3770fb3964f"),
                            SkillName = "Rails"
                        },
                        new
                        {
                            SkillId = new Guid("c7252508-3c2b-47cb-a925-2cf07b056107"),
                            SkillName = "PHP"
                        },
                        new
                        {
                            SkillId = new Guid("f6b620ad-9b20-4fb6-ae61-f50cd04a8dea"),
                            SkillName = "C#"
                        },
                        new
                        {
                            SkillId = new Guid("f8fc1147-22ad-4072-9095-ca12d489fc5c"),
                            SkillName = "ASP.NET"
                        },
                        new
                        {
                            SkillId = new Guid("99395646-971c-44ed-b304-d897622109d2"),
                            SkillName = "Azure"
                        },
                        new
                        {
                            SkillId = new Guid("1f0925ad-4897-4be4-a78e-63b9aac5fe02"),
                            SkillName = "AWS"
                        },
                        new
                        {
                            SkillId = new Guid("d93a9f84-b86b-4323-926f-edab2967ecb2"),
                            SkillName = "GCP"
                        },
                        new
                        {
                            SkillId = new Guid("2f010977-665f-42d8-9b4b-385e387eb488"),
                            SkillName = "SQL"
                        },
                        new
                        {
                            SkillId = new Guid("d9d6bf94-f11a-4447-afa9-97b2a013dc33"),
                            SkillName = "NoSQL"
                        },
                        new
                        {
                            SkillId = new Guid("f5209920-d986-482e-9a51-92de4e22a3d0"),
                            SkillName = "Docker"
                        },
                        new
                        {
                            SkillId = new Guid("3c6b7582-f0a9-434d-91f0-ec69fd136703"),
                            SkillName = "Kubernetes"
                        },
                        new
                        {
                            SkillId = new Guid("ecc4e664-10cf-4944-9a0c-f70487108470"),
                            SkillName = "GraphQL"
                        },
                        new
                        {
                            SkillId = new Guid("d87d6309-278e-4a4e-a8e1-2b3312917579"),
                            SkillName = "SASS"
                        },
                        new
                        {
                            SkillId = new Guid("5df32bce-0f27-45be-8927-b4c4c5580645"),
                            SkillName = "LESS"
                        },
                        new
                        {
                            SkillId = new Guid("e7503659-82db-42b4-afd5-5a4dc82dad33"),
                            SkillName = "Webpack"
                        },
                        new
                        {
                            SkillId = new Guid("4500f23c-8c15-477d-83a0-316c5efa5b21"),
                            SkillName = "Babel"
                        },
                        new
                        {
                            SkillId = new Guid("2f5c89da-f94a-4158-96b7-6b8a85f1ad8b"),
                            SkillName = "Redux"
                        },
                        new
                        {
                            SkillId = new Guid("b9150130-5db7-4e76-9cd6-7959ca3be7ec"),
                            SkillName = "MobX"
                        },
                        new
                        {
                            SkillId = new Guid("5a3c9b0f-fb39-4d64-aab1-923931762b08"),
                            SkillName = "Jest"
                        },
                        new
                        {
                            SkillId = new Guid("ca10ea06-72e3-439e-b659-c9748ba0ff62"),
                            SkillName = "Mocha"
                        },
                        new
                        {
                            SkillId = new Guid("8db9bfc6-2218-494d-8067-766d39a1387a"),
                            SkillName = "Chai"
                        },
                        new
                        {
                            SkillId = new Guid("39ba5f0a-0afb-47eb-959e-6af9bedcff94"),
                            SkillName = "Cucumber"
                        },
                        new
                        {
                            SkillId = new Guid("48f24c77-8a9a-4340-bfb7-aaf99f4089e8"),
                            SkillName = "C++"
                        },
                        new
                        {
                            SkillId = new Guid("55972392-507a-44ec-98a6-fc5d826528b9"),
                            SkillName = "C"
                        },
                        new
                        {
                            SkillId = new Guid("f2d48105-cbce-444b-b2c6-d49417c3d00e"),
                            SkillName = "Go"
                        },
                        new
                        {
                            SkillId = new Guid("33a1bdb7-382b-4e21-a656-dfe55fa2423d"),
                            SkillName = "Rust"
                        },
                        new
                        {
                            SkillId = new Guid("707f6128-094c-4a8d-96a8-b122fa1e7fb4"),
                            SkillName = "Perl"
                        },
                        new
                        {
                            SkillId = new Guid("d607d5c7-1761-4bc6-85eb-2cfaf977e900"),
                            SkillName = "Shell Scripting"
                        },
                        new
                        {
                            SkillId = new Guid("42dac450-619a-4191-9ef5-5abe5ad3232f"),
                            SkillName = "PowerShell"
                        },
                        new
                        {
                            SkillId = new Guid("44a9b731-72b2-4cf9-8f84-9d4a250c704e"),
                            SkillName = "Terraform"
                        },
                        new
                        {
                            SkillId = new Guid("74734376-54d0-4a0d-a2fd-ba480e00ff19"),
                            SkillName = "Ansible"
                        },
                        new
                        {
                            SkillId = new Guid("0eef01ea-2f47-48fb-a23e-acf42fe3c367"),
                            SkillName = "Puppet"
                        },
                        new
                        {
                            SkillId = new Guid("46560cbc-ce1a-401b-bbde-851c00f3e066"),
                            SkillName = "Chef"
                        },
                        new
                        {
                            SkillId = new Guid("cba06e99-5a11-4f0f-a8a6-26ae35fcf3be"),
                            SkillName = "Splunk"
                        },
                        new
                        {
                            SkillId = new Guid("eec65160-80f1-4310-beee-9fe3eb9e0006"),
                            SkillName = "ELK Stack"
                        },
                        new
                        {
                            SkillId = new Guid("b15edd52-bbad-4492-bd53-4606abcd2eae"),
                            SkillName = "Prometheus"
                        },
                        new
                        {
                            SkillId = new Guid("e121d852-5a9a-4607-bbbd-586630d7dc85"),
                            SkillName = "Grafana"
                        },
                        new
                        {
                            SkillId = new Guid("9d2a8c5c-2547-4a29-8b71-17f3d0556934"),
                            SkillName = "Jenkins"
                        },
                        new
                        {
                            SkillId = new Guid("a72968e2-2895-4824-820d-d2e3d4240cc9"),
                            SkillName = "CircleCI"
                        },
                        new
                        {
                            SkillId = new Guid("8fad9c4b-b629-41cc-9cd1-07039603d63f"),
                            SkillName = "Travis CI"
                        },
                        new
                        {
                            SkillId = new Guid("a5df2f64-7237-46fd-ab6a-a0d9317c84d5"),
                            SkillName = "Git"
                        },
                        new
                        {
                            SkillId = new Guid("683d8bd3-2226-498f-9f6b-5e37f3e1ea6c"),
                            SkillName = "Mercurial"
                        },
                        new
                        {
                            SkillId = new Guid("51a34456-5f21-4211-8f82-73f531989268"),
                            SkillName = "Subversion"
                        },
                        new
                        {
                            SkillId = new Guid("e4271448-d0fc-4c55-938c-1bd838e27030"),
                            SkillName = "Project Management"
                        },
                        new
                        {
                            SkillId = new Guid("f72a8417-c796-4728-b601-90c87d031e6e"),
                            SkillName = "Agile Methodology"
                        },
                        new
                        {
                            SkillId = new Guid("a4dc887b-1d5d-495e-a27f-ae5e3a84d2c5"),
                            SkillName = "Scrum"
                        },
                        new
                        {
                            SkillId = new Guid("f69de935-2135-473a-9865-11bbd3155a62"),
                            SkillName = "Kanban"
                        },
                        new
                        {
                            SkillId = new Guid("cfa91f61-c2bd-4d4d-85e3-ba976fd50ed7"),
                            SkillName = "Communication"
                        },
                        new
                        {
                            SkillId = new Guid("5e67dc71-9cdb-420c-aa38-275efc8311a2"),
                            SkillName = "Teamwork"
                        },
                        new
                        {
                            SkillId = new Guid("4dc9ab64-9344-44fc-a843-c807f8b9ca92"),
                            SkillName = "Leadership"
                        },
                        new
                        {
                            SkillId = new Guid("99ee399d-af03-42cf-927c-9db221c3a22f"),
                            SkillName = "Problem-Solving"
                        },
                        new
                        {
                            SkillId = new Guid("3887993f-4914-40c0-bb82-0ceb408ed842"),
                            SkillName = "Time Management"
                        },
                        new
                        {
                            SkillId = new Guid("c1afa4d7-b212-4b22-b885-14739115dc5d"),
                            SkillName = "Critical Thinking"
                        },
                        new
                        {
                            SkillId = new Guid("729f5973-0dc2-4547-a571-5ed26aa9ffef"),
                            SkillName = "Creativity"
                        },
                        new
                        {
                            SkillId = new Guid("290ce652-9058-4c39-b2c2-2da9a4f8c5b9"),
                            SkillName = "Adaptability"
                        },
                        new
                        {
                            SkillId = new Guid("2e283682-b22d-4f84-9b9e-e7a129afd59f"),
                            SkillName = "Attention to Detail"
                        },
                        new
                        {
                            SkillId = new Guid("e8afb451-acdb-403a-8adc-d784b2e1309a"),
                            SkillName = "Conflict Resolution"
                        },
                        new
                        {
                            SkillId = new Guid("aae70555-78ec-415d-b5f3-42afc862d29d"),
                            SkillName = "Negotiation"
                        },
                        new
                        {
                            SkillId = new Guid("21f984db-b474-41ef-861d-edb490d85991"),
                            SkillName = "Customer Service"
                        });
                });

            modelBuilder.Entity("Job_Portal_Application.Models.Title", b =>
                {
                    b.Property<Guid>("TitleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TitleName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("TitleId");

                    b.ToTable("Titles");

                    b.HasData(
                        new
                        {
                            TitleId = new Guid("62a41323-7693-4eba-b6e2-dc9a1f92e0fa"),
                            TitleName = "Full Stack Developer"
                        },
                        new
                        {
                            TitleId = new Guid("f83f8e5c-7dc7-457c-9dd5-4d3beb716a89"),
                            TitleName = "Front End Developer"
                        },
                        new
                        {
                            TitleId = new Guid("450f99fc-ed12-4be0-9e98-fb1f9244e97d"),
                            TitleName = "Back End Developer"
                        },
                        new
                        {
                            TitleId = new Guid("8020a6cb-489c-4a7b-9576-6632a15e7913"),
                            TitleName = "Software Engineer"
                        },
                        new
                        {
                            TitleId = new Guid("6fea5776-381f-4c67-b513-0bd08bff5db0"),
                            TitleName = "Data Scientist"
                        },
                        new
                        {
                            TitleId = new Guid("5c7ad542-f866-4dbf-a987-17efbe36cf15"),
                            TitleName = "DevOps Engineer"
                        },
                        new
                        {
                            TitleId = new Guid("55b4ecc7-29a2-493d-b010-96f1cc499055"),
                            TitleName = "Product Manager"
                        },
                        new
                        {
                            TitleId = new Guid("9ad9a565-b662-4ea6-982a-3631928411c3"),
                            TitleName = "Project Manager"
                        },
                        new
                        {
                            TitleId = new Guid("82e2c5b1-1cae-40ce-a5bd-0df048a82a95"),
                            TitleName = "Business Analyst"
                        },
                        new
                        {
                            TitleId = new Guid("d49a1ec3-8602-4c65-9de3-7b26766a32e2"),
                            TitleName = "QA Engineer"
                        },
                        new
                        {
                            TitleId = new Guid("359ba66a-1759-45a3-85c7-9f795e90a87c"),
                            TitleName = "UI/UX Designer"
                        },
                        new
                        {
                            TitleId = new Guid("11cf87ad-e59c-4c96-8882-b078b71376d4"),
                            TitleName = "Mobile Developer"
                        },
                        new
                        {
                            TitleId = new Guid("234a5a98-6b7a-4897-bd15-80a29ab4156f"),
                            TitleName = "Security Analyst"
                        },
                        new
                        {
                            TitleId = new Guid("4d2629f5-df58-4530-bde0-e277629dbc1b"),
                            TitleName = "Network Engineer"
                        },
                        new
                        {
                            TitleId = new Guid("f8d4eb69-f4ce-4d1c-a107-5f093014b786"),
                            TitleName = "Systems Administrator"
                        },
                        new
                        {
                            TitleId = new Guid("460d89b4-db80-4617-bca2-f513e439369c"),
                            TitleName = "Database Administrator"
                        },
                        new
                        {
                            TitleId = new Guid("e014b4f5-2f41-40a2-9d11-a4028f8d9e35"),
                            TitleName = "Cloud Architect"
                        },
                        new
                        {
                            TitleId = new Guid("02234fd3-23e8-4ae8-a1c8-36d110492232"),
                            TitleName = "Machine Learning Engineer"
                        },
                        new
                        {
                            TitleId = new Guid("c7f99d8b-24f0-4f24-8609-0fbea045892e"),
                            TitleName = "Artificial Intelligence Engineer"
                        },
                        new
                        {
                            TitleId = new Guid("347da339-c387-4220-b2e3-5ba09da5c192"),
                            TitleName = "Technical Support Engineer"
                        },
                        new
                        {
                            TitleId = new Guid("56ebadd3-e410-4a12-8c03-dca29a1ebc2c"),
                            TitleName = "Cloud Engineer"
                        },
                        new
                        {
                            TitleId = new Guid("57cca890-24c5-44ea-a6f0-0bc907fdc374"),
                            TitleName = "Database Developer"
                        },
                        new
                        {
                            TitleId = new Guid("1a2b81dc-eb29-4b5f-a5c8-af1467f14960"),
                            TitleName = "Blockchain Developer"
                        },
                        new
                        {
                            TitleId = new Guid("7c0ab400-d1ec-49a2-b533-484be6bfa8c1"),
                            TitleName = "Game Developer"
                        },
                        new
                        {
                            TitleId = new Guid("7e9b8c2c-1ac9-48b1-9ad2-f1dfbe630908"),
                            TitleName = "VR/AR Developer"
                        },
                        new
                        {
                            TitleId = new Guid("74798d5d-55d1-4277-b02a-a2c4b4f606c0"),
                            TitleName = "Site Reliability Engineer"
                        },
                        new
                        {
                            TitleId = new Guid("201d4509-a9c8-4fd4-97c1-8c27b388bac0"),
                            TitleName = "Embedded Systems Engineer"
                        },
                        new
                        {
                            TitleId = new Guid("ddcd1966-dc1d-4fa6-9ce5-d9dc959a8773"),
                            TitleName = "Firmware Engineer"
                        },
                        new
                        {
                            TitleId = new Guid("328607f7-7355-4ae1-b5a2-591e4abdfa18"),
                            TitleName = "IoT Engineer"
                        },
                        new
                        {
                            TitleId = new Guid("8ba56c3f-4e68-448c-8538-32a66e5aa07f"),
                            TitleName = "Robotics Engineer"
                        },
                        new
                        {
                            TitleId = new Guid("99706fbc-89c9-458c-9396-cc7d16f64ff6"),
                            TitleName = "Computer Vision Engineer"
                        },
                        new
                        {
                            TitleId = new Guid("44acd124-2635-421e-8d1f-48de814ed77b"),
                            TitleName = "Natural Language Processing Engineer"
                        },
                        new
                        {
                            TitleId = new Guid("12eb90b8-5d6c-457b-9906-4ba820efb28f"),
                            TitleName = "Bioinformatics Specialist"
                        },
                        new
                        {
                            TitleId = new Guid("e4cc1e13-9d4d-4530-8e97-68d47eb99d66"),
                            TitleName = "Cryptographer"
                        },
                        new
                        {
                            TitleId = new Guid("a271982f-4f51-4680-8704-99e9476b02a4"),
                            TitleName = "Penetration Tester"
                        },
                        new
                        {
                            TitleId = new Guid("f2a7d6c6-6e8c-4320-a793-948b00b31d66"),
                            TitleName = "Incident Response Analyst"
                        },
                        new
                        {
                            TitleId = new Guid("f842b94c-7c63-4a58-b9a0-f864e603921f"),
                            TitleName = "Cloud Security Engineer"
                        },
                        new
                        {
                            TitleId = new Guid("61c0e3f2-c785-4c1b-b29e-61bc15e1a6a9"),
                            TitleName = "Ethical Hacker"
                        },
                        new
                        {
                            TitleId = new Guid("5a2c5b99-4c24-4e07-a485-cfe2175aba89"),
                            TitleName = "Digital Forensics Specialist"
                        },
                        new
                        {
                            TitleId = new Guid("de2af90b-ca85-4c26-8b54-f73b2a8fc5aa"),
                            TitleName = "IT Support Specialist"
                        },
                        new
                        {
                            TitleId = new Guid("402c823d-a968-42ae-978d-0a0a20eb9dd8"),
                            TitleName = "Help Desk Technician"
                        },
                        new
                        {
                            TitleId = new Guid("e3b6a6ec-9f47-4c50-9b2b-af4b072e1884"),
                            TitleName = "Technical Writer"
                        },
                        new
                        {
                            TitleId = new Guid("0ffb7ba9-34ea-4274-af7f-a6c74d6f50cd"),
                            TitleName = "UX Researcher"
                        },
                        new
                        {
                            TitleId = new Guid("57434753-8ad0-4fed-9b61-90f8a6575090"),
                            TitleName = "IT Manager"
                        },
                        new
                        {
                            TitleId = new Guid("2f17b38b-fdae-4dbd-8ff6-4a7e5f4ac77c"),
                            TitleName = "IT Director"
                        },
                        new
                        {
                            TitleId = new Guid("f88e2c5f-2ffa-4b04-9df6-cd05e3ccdd07"),
                            TitleName = "Chief Technology Officer"
                        },
                        new
                        {
                            TitleId = new Guid("22faaa14-baf4-42f4-8382-e6ec74de4c4e"),
                            TitleName = "Scrum Master"
                        },
                        new
                        {
                            TitleId = new Guid("3bdd160e-9a98-4ce4-8432-7f4bd071fc9a"),
                            TitleName = "Agile Coach"
                        },
                        new
                        {
                            TitleId = new Guid("0e26d9df-fe99-43b3-ad9a-efb5aea4406a"),
                            TitleName = "Technical Lead"
                        },
                        new
                        {
                            TitleId = new Guid("499b4652-7fc4-4d31-8318-7b4abec586be"),
                            TitleName = "Software Architect"
                        },
                        new
                        {
                            TitleId = new Guid("ec62eda3-8d8d-465d-9cec-08a233439d60"),
                            TitleName = "Engineering Manager"
                        },
                        new
                        {
                            TitleId = new Guid("1253117d-c1dd-4e07-b970-383f741148eb"),
                            TitleName = "Chief Information Officer"
                        },
                        new
                        {
                            TitleId = new Guid("759ac35b-adc6-40ef-bb9f-0bea5bcd5d56"),
                            TitleName = "Chief Data Officer"
                        },
                        new
                        {
                            TitleId = new Guid("e7eb25a5-17f7-49df-ba36-4297b6758425"),
                            TitleName = "IT Consultant"
                        },
                        new
                        {
                            TitleId = new Guid("8da1213b-cb51-48c7-b1fb-6d4a45616e65"),
                            TitleName = "Enterprise Architect"
                        },
                        new
                        {
                            TitleId = new Guid("03551ca9-f4f0-4b3c-b440-75645b3e5636"),
                            TitleName = "Security Engineer"
                        },
                        new
                        {
                            TitleId = new Guid("2c42e7e9-57a3-4f79-ab43-c48ef1b8b8fb"),
                            TitleName = "Data Engineer"
                        },
                        new
                        {
                            TitleId = new Guid("42ddc4b1-d3fb-486b-9604-220457955a27"),
                            TitleName = "Data Analyst"
                        },
                        new
                        {
                            TitleId = new Guid("f167b948-7861-4091-81ea-7c9cb2b12e62"),
                            TitleName = "Business Intelligence Developer"
                        },
                        new
                        {
                            TitleId = new Guid("0652c58d-33ed-420a-8d17-e638c095c335"),
                            TitleName = "Big Data Engineer"
                        },
                        new
                        {
                            TitleId = new Guid("06a3aec8-1b3b-4ca0-9dba-7488f579ce53"),
                            TitleName = "Hadoop Developer"
                        },
                        new
                        {
                            TitleId = new Guid("a73edaf1-d1a1-4de0-85e5-ef833a26d181"),
                            TitleName = "Solution Architect"
                        },
                        new
                        {
                            TitleId = new Guid("e4fb5696-a239-43bb-87f5-a8f2e9b13441"),
                            TitleName = "DevSecOps Engineer"
                        },
                        new
                        {
                            TitleId = new Guid("fd842360-4729-4888-bd48-19b270b389f4"),
                            TitleName = "Information Security Analyst"
                        },
                        new
                        {
                            TitleId = new Guid("a58b298e-bd0e-4a82-8aa4-74cd3894d9af"),
                            TitleName = "Site Engineer"
                        },
                        new
                        {
                            TitleId = new Guid("77229507-45d7-4c22-8cc1-1596e157dc90"),
                            TitleName = "Hardware Engineer"
                        },
                        new
                        {
                            TitleId = new Guid("acb8b242-4183-4a4c-9db5-33f900f5f4e1"),
                            TitleName = "IT Auditor"
                        },
                        new
                        {
                            TitleId = new Guid("d9ac57da-772e-4505-b0e6-91b803c71860"),
                            TitleName = "Compliance Analyst"
                        },
                        new
                        {
                            TitleId = new Guid("ce9c3d65-0a30-4231-ba58-ac61e503e563"),
                            TitleName = "Quality Assurance Manager"
                        },
                        new
                        {
                            TitleId = new Guid("3f25f95d-cbb9-4ae2-83fd-c1c6a599e693"),
                            TitleName = "IT Operations Manager"
                        },
                        new
                        {
                            TitleId = new Guid("d6f02ea4-bd0d-4710-a454-b38403294fc8"),
                            TitleName = "Release Manager"
                        },
                        new
                        {
                            TitleId = new Guid("7c22670b-a233-4452-ba4f-68787ef3d185"),
                            TitleName = "Build Engineer"
                        },
                        new
                        {
                            TitleId = new Guid("c12752c1-a83a-4ec2-800c-d54ffaf69bb4"),
                            TitleName = "Configuration Manager"
                        },
                        new
                        {
                            TitleId = new Guid("f74604db-11db-46a6-8475-fbcdc3aa2d4c"),
                            TitleName = "IT Trainer"
                        },
                        new
                        {
                            TitleId = new Guid("95219e34-d316-4a94-8003-67585e27bc72"),
                            TitleName = "ERP Consultant"
                        },
                        new
                        {
                            TitleId = new Guid("ddccaf80-4aec-4f7e-a51c-75560ad7c209"),
                            TitleName = "CRM Developer"
                        },
                        new
                        {
                            TitleId = new Guid("5937378f-aee6-4db0-913f-1add2289d292"),
                            TitleName = "Business Systems Analyst"
                        },
                        new
                        {
                            TitleId = new Guid("5bba5873-a5e8-4952-8b49-3b0c38eb02d4"),
                            TitleName = "Systems Analyst"
                        },
                        new
                        {
                            TitleId = new Guid("e8f66c9b-597e-4954-8ff2-0d6ad19c4f46"),
                            TitleName = "Network Architect"
                        },
                        new
                        {
                            TitleId = new Guid("e611bfb4-3152-41c1-a7bc-b97874847d91"),
                            TitleName = "Telecommunications Specialist"
                        },
                        new
                        {
                            TitleId = new Guid("911d4aa9-52c3-4995-9e19-f31c800efe5e"),
                            TitleName = "IT Procurement Manager"
                        },
                        new
                        {
                            TitleId = new Guid("340ab93c-4a0c-4899-8c96-dc56ae26c09f"),
                            TitleName = "Enterprise Systems Manager"
                        },
                        new
                        {
                            TitleId = new Guid("9d3ddbe6-ccdb-41bd-99f7-ac876296a783"),
                            TitleName = "Chief Information Security Officer"
                        },
                        new
                        {
                            TitleId = new Guid("8bf99458-5447-4ff6-806d-e7e0f9f3e6eb"),
                            TitleName = "Information Technology Specialist"
                        },
                        new
                        {
                            TitleId = new Guid("e259ef42-5184-4b54-be4d-f4e0bcf9f2bc"),
                            TitleName = "Application Support Engineer"
                        },
                        new
                        {
                            TitleId = new Guid("931ace33-da72-43b4-ae30-b877572c5cf1"),
                            TitleName = "IT Project Coordinator"
                        },
                        new
                        {
                            TitleId = new Guid("02c4d41a-47b8-4f06-90dc-891c76b908ce"),
                            TitleName = "IT Project Manager"
                        },
                        new
                        {
                            TitleId = new Guid("09097183-5edb-4e2b-bd5b-89d1197dc97d"),
                            TitleName = "IT Director"
                        },
                        new
                        {
                            TitleId = new Guid("394da39c-3511-4f2d-a42c-2dd41f11cb68"),
                            TitleName = "Chief Information Officer"
                        },
                        new
                        {
                            TitleId = new Guid("757fada1-34ac-485e-938b-6c98d1d4e20c"),
                            TitleName = "Data Privacy Officer"
                        },
                        new
                        {
                            TitleId = new Guid("a2cbb931-e64b-48d3-b52a-2e5803ec725f"),
                            TitleName = "Systems Integrator"
                        },
                        new
                        {
                            TitleId = new Guid("e6812a2c-4c66-42f3-97fa-b729ffe94efb"),
                            TitleName = "Software Development Manager"
                        });
                });

            modelBuilder.Entity("Job_Portal_Application.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AboutMe")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CredentialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Dob")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phonenumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortfolioLink")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResumeUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("UserId");

                    b.HasIndex("CredentialId")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("415fec10-1fe1-4334-86fe-810a925df1c6"),
                            CredentialId = new Guid("bf0e4d0f-f8d4-4bb5-839e-2f34d9f6c6a4"),
                            Dob = new DateOnly(1, 1, 1),
                            Email = "Admin@jobportal.com",
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("Job_Portal_Application.Models.UserSkills", b =>
                {
                    b.Property<Guid>("UserSkillsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserSkillsId");

                    b.HasIndex("SkillId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSkills");
                });

            modelBuilder.Entity("Job_Portal_Application.Models.AreasOfInterest", b =>
                {
                    b.HasOne("Job_Portal_Application.Models.Title", "Title")
                        .WithMany()
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Job_Portal_Application.Models.User", null)
                        .WithMany("AreasOfInterests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Title");
                });

            modelBuilder.Entity("Job_Portal_Application.Models.Company", b =>
                {
                    b.HasOne("Job_Portal_Application.Models.Credential", "Credential")
                        .WithOne()
                        .HasForeignKey("Job_Portal_Application.Models.Company", "CredentialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Credential");
                });

            modelBuilder.Entity("Job_Portal_Application.Models.Education", b =>
                {
                    b.HasOne("Job_Portal_Application.Models.User", null)
                        .WithMany("Educations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Job_Portal_Application.Models.Experience", b =>
                {
                    b.HasOne("Job_Portal_Application.Models.Title", "Title")
                        .WithMany()
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Job_Portal_Application.Models.User", null)
                        .WithMany("Experiences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Title");
                });

            modelBuilder.Entity("Job_Portal_Application.Models.Job", b =>
                {
                    b.HasOne("Job_Portal_Application.Models.Company", "Company")
                        .WithMany("Jobs")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Job_Portal_Application.Models.Title", "Title")
                        .WithMany()
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("Job_Portal_Application.Models.JobActivity", b =>
                {
                    b.HasOne("Job_Portal_Application.Models.Job", "Job")
                        .WithMany("JobActivities")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Job_Portal_Application.Models.User", "User")
                        .WithMany("JobActivities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Job_Portal_Application.Models.JobSkills", b =>
                {
                    b.HasOne("Job_Portal_Application.Models.Job", "Job")
                        .WithMany("JobSkills")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Job_Portal_Application.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Job_Portal_Application.Models.User", b =>
                {
                    b.HasOne("Job_Portal_Application.Models.Credential", "Credential")
                        .WithOne()
                        .HasForeignKey("Job_Portal_Application.Models.User", "CredentialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Credential");
                });

            modelBuilder.Entity("Job_Portal_Application.Models.UserSkills", b =>
                {
                    b.HasOne("Job_Portal_Application.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Job_Portal_Application.Models.User", "User")
                        .WithMany("UserSkills")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Job_Portal_Application.Models.Company", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("Job_Portal_Application.Models.Job", b =>
                {
                    b.Navigation("JobActivities");

                    b.Navigation("JobSkills");
                });

            modelBuilder.Entity("Job_Portal_Application.Models.User", b =>
                {
                    b.Navigation("AreasOfInterests");

                    b.Navigation("Educations");

                    b.Navigation("Experiences");

                    b.Navigation("JobActivities");

                    b.Navigation("UserSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
