// <auto-generated />
using DoctorClinicApi.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoctorClinicApi.Migrations
{
    [DbContext(typeof(DoctorClinicContext))]
    [Migration("20240515190401_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DoctorClinicApi.Model.Doctor", b =>
                {
                    b.Property<int>("Doctorid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Doctorid"));

                    b.Property<string>("Doctorname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Experience")
                        .HasColumnType("real");

                    b.Property<string>("Specification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Doctorid");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Doctorid = 1,
                            Doctorname = "srikanth",
                            Experience = 2f,
                            Specification = "Mbbs"
                        },
                        new
                        {
                            Doctorid = 3,
                            Doctorname = "Sugan",
                            Experience = 2f,
                            Specification = "Mbbs"
                        },
                        new
                        {
                            Doctorid = 2,
                            Doctorname = "Barath",
                            Experience = 5f,
                            Specification = "Mbbs,md"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
