version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - job-portal-network

  jobportal:
    image: srikanthkarthi/job_portal_application-jobportal:latest
    depends_on:
      - sqlserver
      - jobportal-s3 
    networks:
      - job-portal-network
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=JobPortalDB;User Id=sa;Password=YourStrong@Passw0rd;Encrypt=false;TrustServerCertificate=True"
      MinIO__ServiceUrl: "http://jobportal-s3:9000"
      MinIO__AccessKey: "minioadmin"
      MinIO__SecretKey: "minioadmin"
      MinIO__BucketName: "job-portal-application"

  jobportal-s3: 
    image: minio/minio:latest
    container_name: jobportal-s3
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --address :9000 --console-address :9001
    volumes:
      - minio_data:/data
    networks:
      - job-portal-network

networks:
  job-portal-network:
    driver: bridge

volumes:
  minio_data:
